version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "nuget"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    open-pull-requests-limit: 10
