parameters:
  - name: platforms
    type: object
    default:
      - name: Windows_Debug
        poolImage: 'windows-2025'
        configuration: debug
      - name: Windows_Release
        poolImage: 'windows-2025'
        configuration: release
      - name: macOS_Debug
        poolImage: 'macOS-15'
        configuration: debug

jobs:
  - ${{ each platform in parameters.platforms }}:
    - job: Build_${{ replace(platform.name, ' ', '_') }}
      displayName: 'Build - ${{ platform.name }}'
      pool:
        vmImage: ${{ platform.poolImage }}
      steps:
        - checkout: self
        - template: setup-tools.yml
        - script: dotnet build DeviceRunners.sln --configuration ${{ platform.configuration }} /bl:./artifacts/logs/msbuild-build.binlog
          displayName: 'Build'
        - publish: ./artifacts/logs
          artifact: 'Logs - Build ${{ platform.poolImage }} (${{ platform.configuration }})'
          displayName: 'Upload Logs'
          condition: always()
