parameters:
  - name: poolImage
    type: string
    default: 'windows-2025'
  - name: nupkgMajor
    type: string
    default: '0.999'

jobs:
  - job: Pack
    pool:
      vmImage: ${{ parameters.poolImage }}
    variables:
      NUPKG_MAJOR: ${{ parameters.nupkgMajor }}
    steps:
      - checkout: self
      - template: setup-tools.yml
      - pwsh: |
          $VERSION = "$(NUPKG_MAJOR)-ci.$(Build.BuildId)"
          Write-Host "PACKAGE VERSION: $VERSION"
          dotnet pack --output ./artifacts/nugets --configuration release -p:PackageVersion=$VERSION /bl:./artifacts/logs/msbuild-pack.binlog
        displayName: 'Pack NuGets'
      - publish: ./artifacts/nugets
        artifact: 'NuGet'
        displayName: 'Upload NuGet Artifacts'
      - publish: ./artifacts/logs
        artifact: 'Pack Logs'
        displayName: 'Upload Logs'
        condition: always()
