parameters:
  - name: poolImage
    type: string
    default: 'macOS-15'
  - name: targetFramework
    type: string
    default: 'net10.0-maccatalyst'
  - name: runtimeIdentifier
    type: string
    default: 'maccatalyst-x64'
  - name: configuration
    type: string
    default: 'release'

jobs:
  - job: dotnet_test_macOS
    displayName: 'dotnet test macOS'
    pool:
      vmImage: ${{ parameters.poolImage }}
    variables:
      TEST_TARGET_FRAMEWORK: ${{ parameters.targetFramework }}
      TEST_RUNTIME_IDENTIFIER: ${{ parameters.runtimeIdentifier }}
      TEST_CONFIGURATION: ${{ parameters.configuration }}
    steps:
      - checkout: self
      - template: setup-tools.yml
      - script: dotnet publish src/DeviceRunners.Cli/DeviceRunners.Cli.csproj -f net10.0 -r osx-x64 -p:PublishForTargetsPackage=true -o src/DeviceRunners.Testing.Targets/tools/osx-x64
        displayName: 'Publish CLI Tool Binaries'
      - script: |
          dotnet test sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj \
            -f $(TEST_TARGET_FRAMEWORK) \
            -r $(TEST_RUNTIME_IDENTIFIER) \
            -c $(TEST_CONFIGURATION) \
            /bl:./artifacts/logs/msbuild-test.binlog
        displayName: 'Run Tests'
      - publish: ./artifacts
        artifact: 'Test Results (dotnet test) - macOS'
        displayName: 'Upload Artifacts'
        condition: always()
