parameters:
  - name: platforms
    type: object
    default:
      - name: x64
        poolImage: 'macOS-15'
        testRid: maccatalyst-x64
        configuration: release
  - name: targetFramework
    type: string
    default: net10.0-maccatalyst

jobs:
  - ${{ each platform in parameters.platforms }}:
    - job: TCP_macOS_${{ replace(platform.name, ' ', '_') }}
      displayName: 'TCP macOS - ${{ platform.name }}'
      pool:
        vmImage: ${{ platform.poolImage }}
      variables:
        TEST_TARGET_FRAMEWORK: ${{ parameters.targetFramework }}
        TEST_RUNTIME_IDENTIFIER: ${{ platform.testRid }}
        TEST_CONFIGURATION: ${{ platform.configuration }}
      timeoutInMinutes: 30
      steps:
        - checkout: self
        - template: validate-arch.yml
          parameters:
            runtimeIdentifier: ${{ platform.testRid }}
        - template: setup-tools.yml
        - script: |
            dotnet pack src/DeviceRunners.Cli/DeviceRunners.Cli.csproj -c release
            dotnet tool install --global --add-source artifacts/package/release DeviceRunners.Cli
          displayName: 'Build and Install CLI Tool'
        - script: |
            dotnet publish sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj \
              -f $(TEST_TARGET_FRAMEWORK) \
              -r $(TEST_RUNTIME_IDENTIFIER) \
              -c $(TEST_CONFIGURATION) \
              -p:TestingMode=NonInteractiveVisual \
              /bl:./artifacts/logs/msbuild-publish.binlog
          displayName: 'Publish App'
        - script: |
            app_bundle=$(find artifacts/bin/DeviceTestingKitApp.DeviceTests/$(TEST_CONFIGURATION)_$(TEST_TARGET_FRAMEWORK)_$(TEST_RUNTIME_IDENTIFIER) -name "*.app" -type d)
            device-runners macos test --app "$app_bundle" --results-directory artifacts/test-results
          displayName: 'Run Tests'
        - script: |
            rm -rf ./artifacts/bin
            rm -rf ./artifacts/obj
          displayName: 'Clean up build artifacts before upload'
          condition: always()
        - publish: ./artifacts
          artifact: 'Test Results (TCP) - macOS (${{ platform.name }})'
          displayName: 'Upload Artifacts'
          condition: always()
