parameters:
  - name: poolImage
    type: string
    default: 'ubuntu-24.04'
  - name: configuration
    type: string
    default: 'release'

jobs:
  - job: dotnet_test_WASM_Browser
    displayName: 'dotnet test WASM Browser'
    pool:
      vmImage: ${{ parameters.poolImage }}
    variables:
      TEST_CONFIGURATION: ${{ parameters.configuration }}
    steps:
      - checkout: self
      - template: setup-tools.yml
      - script: dotnet publish src/DeviceRunners.Cli/DeviceRunners.Cli.csproj -f net10.0 -r linux-x64 -p:PublishForTargetsPackage=true -o src/DeviceRunners.Testing.Targets/tools/linux-x64
        displayName: 'Publish CLI Tool Binaries'
      - script: |
          dotnet test sample/test/DeviceTestingKitApp.BrowserTests/DeviceTestingKitApp.BrowserTests.csproj \
            -c $(TEST_CONFIGURATION) \
            --logger "trx;LogFileName=test-results.trx" \
            /bl:./artifacts/logs/msbuild-test.binlog
        displayName: 'Run Tests'
      - script: |
          rm -rf ./artifacts/bin
          rm -rf ./artifacts/obj
        displayName: 'Clean up build artifacts before upload'
        condition: always()
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        condition: always()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/test-results.trx'
          searchFolder: '$(System.DefaultWorkingDirectory)/artifacts/test-results'
          mergeTestResults: true
          testRunTitle: 'dotnet test WASM Browser'
      - publish: ./artifacts
        artifact: 'Test Results (dotnet test) - WASM Browser'
        displayName: 'Upload Artifacts'
        condition: always()
