parameters:
  - name: poolImage
    type: string
    default: 'windows-2025'
  - name: targetFramework
    type: string
    default: 'net10.0-windows10.0.19041.0'
  - name: runtimeIdentifier
    type: string
    default: 'win10-x64'
  - name: configuration
    type: string
    default: 'release'

jobs:
  - job: TCP_Windows
    pool:
      vmImage: ${{ parameters.poolImage }}
    variables:
      TEST_TARGET_FRAMEWORK: ${{ parameters.targetFramework }}
      TEST_RUNTIME_IDENTIFIER: ${{ parameters.runtimeIdentifier }}
      TEST_CONFIGURATION: ${{ parameters.configuration }}
    steps:
      - checkout: self
      - template: setup-tools.yml
      - pwsh: |
          dotnet test sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj `
            -f $(TEST_TARGET_FRAMEWORK) `
            -c $(TEST_CONFIGURATION) `
            -p:TestingMode=NonInteractiveVisual `
            /bl:./artifacts/logs/msbuild-test.binlog
        displayName: 'Run Tests'
      - pwsh: |
          Remove-Item -Recurse -Force ./artifacts/bin -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force ./artifacts/obj -ErrorAction SilentlyContinue
        displayName: 'Clean up build artifacts before upload'
        condition: always()
      - publish: ./artifacts
        artifact: 'Test Results (TCP) - Windows'
        displayName: 'Upload Artifacts'
        condition: always()
