parameters:
  - name: poolImage
    type: string
    default: 'windows-2025'
  - name: targetFramework
    type: string
    default: 'net10.0-windows10.0.19041.0'
  - name: configuration
    type: string
    default: 'release'

jobs:
  - job: dotnet_test_Windows_EXE
    displayName: 'dotnet test Windows (EXE)'
    pool:
      vmImage: ${{ parameters.poolImage }}
    variables:
      TEST_TARGET_FRAMEWORK: ${{ parameters.targetFramework }}
      TEST_CONFIGURATION: ${{ parameters.configuration }}
    steps:
      - checkout: self
      - template: setup-tools.yml
      - pwsh: dotnet publish src/DeviceRunners.Cli/DeviceRunners.Cli.csproj -f net10.0 -r win-x64 -p:PublishForTargetsPackage=true -o src/DeviceRunners.Testing.Targets/tools/win-x64
        displayName: 'Publish CLI Tool Binaries'
      - pwsh: |
          dotnet test sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj `
            -f $(TEST_TARGET_FRAMEWORK) `
            -c $(TEST_CONFIGURATION) `
            -p:WindowsPackageType=None `
            --logger "trx;LogFileName=test-results.trx" `
            /bl:./artifacts/logs/msbuild-test.binlog
        displayName: 'Run Tests'
      - pwsh: |
          Remove-Item -Recurse -Force ./artifacts/bin -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force ./artifacts/obj -ErrorAction SilentlyContinue
        displayName: 'Clean up build artifacts before upload'
        condition: always()
      - publish: ./artifacts
        artifact: 'Test Results (dotnet test) - Windows (EXE)'
        displayName: 'Upload Artifacts'
        condition: always()
