parameters:
  - name: platforms
    type: object
    default:
      - name: x64
        poolImage: 'macOS-15'
        testRid: maccatalyst-x64
  - name: targetFramework
    type: string
    default: net10.0-maccatalyst
  - name: configuration
    type: string
    default: debug

jobs:
  - ${{ each platform in parameters.platforms }}:
    - job: XHarness_MacCatalyst_${{ replace(platform.name, ' ', '_') }}
      displayName: 'XHarness Mac Catalyst - ${{ platform.name }}'
      pool:
        vmImage: ${{ platform.poolImage }}
      variables:
        TEST_TARGET_FRAMEWORK: ${{ parameters.targetFramework }}
        TEST_RUNTIME_IDENTIFIER: ${{ platform.testRid }}
        TEST_CONFIGURATION: ${{ parameters.configuration }}
      steps:
        - checkout: self
        - template: validate-arch.yml
          parameters:
            runtimeIdentifier: ${{ platform.testRid }}
        - template: setup-tools.yml
        - script: |
            dotnet build sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj \
              -f $(TEST_TARGET_FRAMEWORK) \
              -r $(TEST_RUNTIME_IDENTIFIER) \
              -c $(TEST_CONFIGURATION) \
              -p:TestingMode=XHarness \
              /bl:./artifacts/logs/msbuild-publish.binlog
          displayName: 'Publish App'
        - script: |
            dotnet xharness apple test \
              --target maccatalyst \
              --timeout="00:02:00" \
              --launch-timeout=00:06:00 \
              --app artifacts/bin/DeviceTestingKitApp.DeviceTests/$(TEST_CONFIGURATION)_$(TEST_TARGET_FRAMEWORK)_$(TEST_RUNTIME_IDENTIFIER)/DeviceTestingKitApp.DeviceTests.app \
              --output-directory artifacts/test-results
          displayName: 'Run Tests'
        - script: |
            rm -rf ./artifacts/bin
            rm -rf ./artifacts/obj
          displayName: 'Clean up build artifacts before upload'
          condition: always()
        - publish: ./artifacts
          artifact: 'Test Results (XHarness) - Mac Catalyst (${{ platform.name }})'
          displayName: 'Upload Artifacts'
          condition: always()
