parameters:
  - name: platforms
    type: object
    default:
      - name: Windows
        poolImage: 'windows-2025'
      - name: macOS
        poolImage: 'macOS-15'

jobs:
  - ${{ each platform in parameters.platforms }}:
    - job: Test_${{ replace(platform.name, ' ', '_') }}
      displayName: 'Test - ${{ platform.name }}'
      pool:
        vmImage: ${{ platform.poolImage }}
      steps:
        - checkout: self
        - template: setup-tools.yml
        - script: dotnet test test/DeviceRunners.VisualRunners.Tests --configuration release /bl:./artifacts/logs/msbuild-test.binlog
          displayName: 'Test'
        - publish: ./artifacts/logs
          artifact: 'Logs - Test ${{ platform.poolImage }}'
          displayName: 'Upload Logs'
          condition: always()
