parameters:
  - name: poolImage
    type: string
    default: 'windows-2025'
  - name: targetFramework
    type: string
    default: 'net9.0'

jobs:
  - job: Validate_Template
    displayName: 'Validate Template'
    pool:
      vmImage: ${{ parameters.poolImage }}
    steps:
      - checkout: self
      - template: setup-tools.yml
      - download: current
        artifact: 'NuGet'
        displayName: 'Download NuGet Packages'
      - script: |
          ls -la $(Pipeline.Workspace)/NuGet/
          dotnet new install $(Pipeline.Workspace)/NuGet/DeviceRunners.Templates.*.nupkg
        displayName: 'Install Template'
      - script: |
          mkdir -p ./artifacts/template-test
          cd ./artifacts/template-test
          dotnet new devicerunners -n TemplateValidation --Framework ${{ parameters.targetFramework }}
        displayName: 'Create Project from Template'
      - script: |
          cd ./artifacts/template-test/TemplateValidation
          dotnet build --source $(Pipeline.Workspace)/NuGet --source https://api.nuget.org/v3/index.json \
            /bl:../../logs/msbuild-template-build.binlog
        displayName: 'Build Template Project'
      - script: |
          rm -rf ./artifacts/template-test
        displayName: 'Clean up'
        condition: always()
      - publish: ./artifacts/logs
        artifact: 'Logs - Template Validation'
        displayName: 'Upload Logs'
        condition: always()
