name: Setup Tools

description: Installs and configures all the required tools

inputs:
  xcode-version:
    description: 'The version of Xcode to install.'
    required: false
    default: '26.2'

runs:
  using: composite
  steps:
  - name: Setup Xcode
    uses: maxim-lobanov/setup-xcode@v1
    if: runner.os == 'macOS'
    with:
      xcode-version: ${{ inputs.xcode-version }}
  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 10.0.x
  - name: Show .NET Info
    shell: pwsh
    run: dotnet --info
  - name: Setup .NET MAUI
    if: runner.os == 'Linux'
    shell: pwsh
    run: dotnet workload install maui-android --source https://api.nuget.org/v3/index.json
  - name: Setup .NET MAUI
    if: runner.os != 'Linux'
    shell: pwsh
    run: dotnet workload install maui --source https://api.nuget.org/v3/index.json
  - name: Setup Local .NET Tools
    shell: pwsh
    run: dotnet tool restore
  - name: Build and Install Android Tool from Submodule
    if: runner.os != 'macOS'
    shell: pwsh
    run: |
      dotnet pack external/AndroidSdk.Tools/AndroidSdk.Tool/AndroidSdk.Tool.csproj -c Release -o ./artifacts/tools -p:Version=0.0.0-dev
      dotnet tool install --global --add-source ./artifacts/tools androidsdk.tool
  - name: Build and Install Android & Apple Tools from Submodules
    if: runner.os == 'macOS'
    shell: pwsh
    run: |
      dotnet pack external/AndroidSdk.Tools/AndroidSdk.Tool/AndroidSdk.Tool.csproj -c Release -o ./artifacts/tools -p:Version=0.0.0-dev
      dotnet tool install --global --add-source ./artifacts/tools androidsdk.tool
      git -C external/AppleDev.Tools fetch --unshallow 2>$null; git -C external/AppleDev.Tools fetch --tags 2>$null
      dotnet pack external/AppleDev.Tools/AppleDev.Tool/AppleDev.Tool.csproj -c Release -o ./artifacts/tools
      dotnet tool install --global --add-source ./artifacts/tools appledev.tools
