name: Build

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Windows
            os: windows-2025
          - name: macOS
            os: macos-15-intel
        configuration:
          - debug
          - release
        exclude:
          - platform:
              name: macOS
            configuration: release
    name: Build - ${{ matrix.platform.name }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.platform.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Build
      run: dotnet build DeviceRunners.sln --configuration ${{ matrix.configuration }} /bl:./artifacts/logs/msbuild-build.binlog
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Logs - Build ${{ matrix.platform.name }} (${{ matrix.configuration }})
        path: ./artifacts/logs
