name: Release

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pack:
    name: Pack
    runs-on: windows-2025
    env:
      NUPKG_MAJOR: 0.999
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/setup-tools
    - name: Package NuGets
      shell: pwsh
      run: |
        $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
        echo "PACKAGE VERSION: $VERSION"
        dotnet pack --output ./artifacts/nugets --configuration release -p:PackageVersion=$VERSION /bl:./artifacts/logs/msbuild-pack.binlog
    - uses: actions/upload-artifact@v4
      with:
        name: NuGet
        path: ./artifacts/nugets
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Pack Logs - Windows
        path: ./artifacts/logs

  publish:
    name: Publish NuGet Packages
    needs: pack
    runs-on: windows-2025
    env:
      NUGET_URL: 'https://pkgs.dev.azure.com/mattleibow/OpenSource/_packaging/test-device-runners/nuget/v3/index.json'
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: NuGet
        path: artifacts
    - run: dir artifacts
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        source-url: ${{ env.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_NUGET_TOKEN }}
    - run: dotnet nuget push artifacts\*.nupkg --source $env:NUGET_URL --api-key AzureArtifacts
