name: TCP Android Test

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  android:
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - name: Linux
            os: ubuntu-22.04
            gpu: swiftshader_indirect
          - name: macOS
            os: macos-13
            gpu: guest
    name: Android (${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.os }}
    env:
      TEST_TARGET_FRAMEWORK: net9.0-android
      TEST_RUNTIME_IDENTIFIER: android-x64
      TEST_CONFIGURATION: release
      TEST_EMULATOR_NAME: TCPTestEmulator
      TEST_EMULATOR_IMAGE: system-images;android-34;google_apis;x86_64
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
      with:
        xcode-version: '15.2'
    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '21'
    - name: Build and Install CLI Tool
      run: |
        dotnet pack src/DeviceRunners.Cli/DeviceRunners.Cli.csproj -c ${{ env.TEST_CONFIGURATION }}
        dotnet tool install --global --add-source artifacts/package/${{ env.TEST_CONFIGURATION }} DeviceRunners.Cli
    - name: Install Android SDK Packages
      run: dotnet android sdk install --package 'platform-tools' --package 'emulator' --package '${{ env.TEST_EMULATOR_IMAGE }}'
    - name: Create Emulator
      run: dotnet android avd create --name ${{ env.TEST_EMULATOR_NAME }} --sdk '${{ env.TEST_EMULATOR_IMAGE }}' --force
    - name: Enable KVM
      if: runner.os == 'Linux'
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Start Emulator
      run: dotnet android avd start --name ${{ env.TEST_EMULATOR_NAME }} --gpu ${{ matrix.platform.gpu }} --wait-boot --no-window --no-snapshot --no-audio --no-boot-anim
    - name: Publish App
      run: |
        dotnet publish sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj \
          -f ${{ env.TEST_TARGET_FRAMEWORK }} \
          -r ${{ env.TEST_RUNTIME_IDENTIFIER }} \
          -c ${{ env.TEST_CONFIGURATION }} \
          -p:TestingMode=NonInteractiveVisual \
          -p:AndroidSdkDirectory=$ANDROID_SDK_ROOT \
          /bl:./artifacts/logs/msbuild-publish.binlog
    - name: Run Tests
      run: |
        device-runners android test \
          --app artifacts/bin/DeviceTestingKitApp.DeviceTests/${{ env.TEST_CONFIGURATION }}_${{ env.TEST_TARGET_FRAMEWORK }}_${{ env.TEST_RUNTIME_IDENTIFIER }}/com.companyname.devicetestingkitapp.devicetests-Signed.apk \
          --results-directory artifacts/test-results
    - name: Shutdown the Emulator
      if: always()
      run: $ANDROID_SDK_ROOT/platform-tools/adb emu kill
    - name: Clean up build artifacts before upload
      run: |
        rm -rf ./artifacts/bin
        rm -rf ./artifacts/obj
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test Results (TCP) - Android (${{ matrix.platform.name }})
        path: ./artifacts