name: TCP Windows Test (Unpackaged)

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  windows-unpackaged:
    name: Windows (Unpackaged)
    runs-on: windows-latest
    env:
      TEST_TARGET_FRAMEWORK: net9.0-windows10.0.19041.0
      TEST_RUNTIME_IDENTIFIER: win10-x64
      TEST_CONFIGURATION: release
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Build and Install CLI Tool
      run: |
        dotnet pack src/DeviceRunners.Cli/DeviceRunners.Cli.csproj -c ${{ env.TEST_CONFIGURATION }}
        dotnet tool install --global --add-source artifacts/package/${{ env.TEST_CONFIGURATION }} DeviceRunners.Cli
    - name: Publish App as Unpackaged Executable
      run: |
        dotnet publish sample/test/DeviceTestingKitApp.DeviceTests/DeviceTestingKitApp.DeviceTests.csproj `
          -f ${{ env.TEST_TARGET_FRAMEWORK }} `
          -r ${{ env.TEST_RUNTIME_IDENTIFIER }} `
          -c ${{ env.TEST_CONFIGURATION }} `
          -p:TestingMode=NonInteractiveVisual `
          -p:PublishSingleFile=true `
          -p:SelfContained=true `
          -p:WindowsPackageType=None `
          --output artifacts/publish `
          /bl:./artifacts/logs/msbuild-publish-unpackaged.binlog
    - name: Run Tests with Unpackaged App
      run: |
        $exe = Get-ChildItem "artifacts/publish/DeviceTestingKitApp.DeviceTests.exe"
        device-runners windows test --app $exe --results-directory artifacts/test-results
    - name: Clean up build artifacts before upload
      run: |
        Remove-Item -Recurse -Force ./artifacts/bin -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force ./artifacts/obj -ErrorAction SilentlyContinue
      if: ${{ always() }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test Results (TCP) - Windows Unpackaged
        path: ./artifacts