name: Test

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-14
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Test
      run: dotnet test test/DeviceRunners.VisualRunners.Tests --configuration Release /bl:./artifacts/logs/msbuild-test.binlog
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Logs - ${{ matrix.platform.name }}
        path: ./artifacts/logs
