name: TCP Windows Test

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  windows:
    name: TCP Windows
    runs-on: windows-2025
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test-tcp-windows
