name: TCP iOS Test

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ios:
    name: iOS (x64)
    runs-on: macos-15-intel
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test-tcp-ios
